.github/workflows/integration.yaml
.github/workflows/unit_tests.yaml
sidekick/cli_template/bricks/sidekick/__brick__/packages/{{#lowerCase}}{{name}}{{/lowerCase}}_sidekick/pubspec.yaml
sidekick/test/init_test.dart
sidekick/test/recompile_test.dart

Followup to #10 
CI should now work

Update min sidekick_core version in template

---

.github/workflows/integration.yaml
sidekick_core/lib/src/dart.dart
sidekick_core/lib/src/flutterw.dart

- use `dart.exe`
- execute `flutterw` with `bash`

Make core windows compatible

---

sidekick_core/lib/src/dart_package.dart
sidekick_vault/example/example.dart
sidekick_vault/lib/sidekick_vault.dart
sidekick_vault/lib/src/encrypted_vault_string.dart

```dart
// define encrypted files in vault
final EncryptedVaultString encrypted = vault.encryptedString('secret.txt');
// access the text prompts the passsword
print(encrypted.text);
```

Create EncryptedVaultString that postpones decryption until usage

---

.github/workflows/generate.yaml
.github/workflows/integration.yaml
sidekick/cli_template/bricks/sidekick/__brick__/packages/{{#lowerCase}}{{name}}{{/lowerCase}}_sidekick/pubspec.yaml
sidekick/lib/src/init/init_command.dart
sidekick/lib/src/templates/cli_bundle.g.dart
sidekick/pubspec.yaml
sidekick_core/pubspec.yaml
sidekick_vault/pubspec.yaml

- https://github.com/felangel/mason/pull/208
- Raise minSdk to 2.14

Upgrade to mason 0.1.0-dev.4

---

sidekick/lib/src/init/init_command.dart
sidekick/lib/src/init/name_suggester.dart
sidekick/pubspec.yaml

Add auto name generation

---

sidekick/lib/src/init/init_command.dart

When possible, we should update automatically to the latest `sidekick_core` version

Automatically update the sidekick_core dependency

---

sidekick_vault/test/unlock_test.dart
sidekick_vault/test/vault_command_test.dart

`Env.mock` was removed from `dcli`

Mock environment with withEnvironment

---

sidekick/lib/src/init/init_command.dart

https://twitter.com/passsy/status/1486004405300248583?s=20&t=SCD-zCQBkvEMHRCV2gfP_w

Make entrypoint executable on unix when sidekick is executed on windows

---

sidekick_vault/lib/src/commands/vault_command.dart
sidekick_vault/test/vault_command_test.dart

Allows changing the password of the vault with 
```bash
$ <cli> vault change-password
Changing password for vault 'vault':
Old Password: ****
New Password: ****
```
This can be automated with `--new` and `--old` parameters (see test)

Add 'vault change-password' command

---

sidekick_vault/lib/sidekick_vault.dart
sidekick_vault/lib/src/logging.dart
sidekick_vault/lib/src/vault.dart

Hides the secret on github actions

[vault] Make maskSecret public

---

sidekick/cli_template/.mason/bricks.json

I'm not sure, but this file looks like a temp file which shouldn't be in git 🤔

Remove local mason file in `cli_template`

---

sidekick_vault/lib/src/vault.dart
sidekick_vault/test/delete_test.dart

Allows deletions of vault entries

[vault] Add vault.deleteFile(File)

---

.github/workflows/integration.yaml
.github/workflows/lint.yaml
sidekick/pubspec.lock
sidekick_core/pubspec.yaml

Updated the DCLI constrainst to make integration tests work again

update dcli constraints

---

sidekick_core/CHANGELOG.md
sidekick_core/lib/sidekick_core.dart
sidekick_core/lib/src/commands/plugins_command.dart
sidekick_core/lib/src/dart_runtime.dart
sidekick_core/lib/src/pub/pub.dart
sidekick_core/lib/src/repository.dart
sidekick_core/lib/src/sidekick_package.dart
sidekick_core/pubspec.yaml

Extract all changes of `sidekick_core` in #58

Adds the plugin command to sidekick_core

---

sidekick/lib/src/init/name_suggester.dart
sidekick_core/lib/src/dart_package.dart
sidekick_core/test/dart_package.dart

Will be useful for the plugin template generator #61

[core] Add isValidPubPackageName

---

sidekick/cli_template/bricks/package/__brick__/pubspec.yaml
sidekick/lib/sidekick.dart
sidekick/lib/src/plugins/plugins_command.dart
sidekick/lib/src/templates/package_bundle.g.dart
sidekick/pubspec.lock
sidekick/pubspec.yaml

Allows creating a plugin with the `sidekick` cli

Add plugins create command to sidekick cli

---

.github/workflows/integration.yaml
sidekick/pubspec.yaml
sidekick/test/plugins_test.dart
sidekick/test/util/local_testing.dart
sidekick_core/lib/sidekick_core.dart
sidekick_core/lib/src/commands/plugins/create_plugin_command.dart
sidekick_core/lib/src/commands/plugins/create_templates/install_only.dart
sidekick_core/lib/src/commands/plugins/create_templates/shared_code.dart
sidekick_core/lib/src/commands/plugins/create_templates/shared_command.dart
sidekick_core/lib/src/commands/plugins/create_templates/template_generator.dart
sidekick_core/lib/src/dart.dart

Make global `sidekick plugins create` work

---

sidekick_core/lib/sidekick_core.dart
sidekick_core/test/init_test.dart

Those exits make testing of #84 impossible. Let's change that

Throw OutOfCommandRunnerScopeException instead of existing the process with error()

---

.github/workflows/lint.yaml
sidekick_core/lib/sidekick_core.dart
sidekick_core/lib/src/commands/plugins/create_plugin_command.dart
sidekick_core/lib/src/commands/plugins/create_templates/install_only.dart
sidekick_core/lib/src/commands/plugins/create_templates/plugin_template_generator.dart
sidekick_core/lib/src/commands/plugins/create_templates/shared_code.dart
sidekick_core/lib/src/commands/plugins/create_templates/shared_command.dart
sidekick_core/lib/src/file_util.dart
sidekick_core/lib/src/template/download_dart.sh.template.dart
sidekick_core/lib/src/template/entrypoint.template.dart
sidekick_core/lib/src/template/install.sh.template.dart
sidekick_core/lib/src/template/run.sh.template.dart
sidekick_core/lib/src/template/sidekick_config.sh.template.dart
sidekick_core/lib/src/template/sidekick_package.template.dart
sidekick_core/test/template_test.dart

`sidekick_core` part 1 of #101
This should be merged before the changes in the cli can be applied

Move sidekick template to sidekick_core

---

sidekick_core/lib/src/template/sidekick_package.template.dart
sidekick_core/test/local_testing.dart
sidekick_core/test/sidekick_package_template_test.dart

Fix invalid sidekick template for cli names containing underscores 

---

sidekick_core/lib/src/commands/deps_command.dart
sidekick_core/lib/src/dart_package.dart

exclude is part of the API but wasn't implemented 🙈

Fix DepsCommand(exclude: )

---

sidekick_core/lib/sidekick_core.dart
sidekick_core/pubspec.yaml
sidekick_core/test/init_test.dart

Allows access when checking for updates
Unblocks #111

Add sidekick_core version to sidekick_core package source

---

sk_sidekick/lib/sk_sidekick.dart
sk_sidekick/pubspec.lock
sk_sidekick/pubspec.yaml

Exclusion wasn't really working before

Fix `sk deps` exclusion

---

sidekick_core/lib/src/flutter.dart
sidekick_core/test/flutter_test.dart

systemFlutterSdk: check for env.FLUTTER_ROOT

---

sidekick_plugin_installer/lib/src/register_plugin.dart

Prevent duplicate addition of commands.

---

sidekick/test/plugins_test.dart
sidekick/test/util/cli_runner.dart
sidekick_core/lib/src/commands/plugins/create_templates/shared_code.dart
sidekick_plugin_installer/lib/src/plugin_context.dart
sidekick_test/lib/src/local_testing.dart

shared-code template: copy directly from file instead of from string

---

sidekick_core/lib/src/commands/update_command.dart
sidekick_core/test/update_command_test.dart

No, changes. Just documentation
And tests now print the output, instead of swallowing it for assertions

Refactor Update Command

---

.github/workflows/format.yaml
.github/workflows/lint.yaml
.github/workflows/unit_tests.yaml
sidekick_vault/pubspec.yaml
sidekick_vault/test/vault_command_test.dart
sk_sidekick/lib/sk_sidekick.dart
sk_sidekick/lib/src/commands/verify_publish_state_command.dart

Makes sure we run CI for all packages

Update CI workflows

---

sidekick_core/lib/src/update/migration.dart
sidekick_core/lib/src/update_sidekick_cli.dart
sidekick_core/lib/src/version_checker.dart
sidekick_core/pubspec.yaml
sidekick_core/test/update/patches/157_fix_usage_message.patch_test.dart
sidekick_core/test/update/update_dart_version_test.dart

During `<cli> sidekick update` the sdk will be migrated to the latest stable Dart SDK version

[Update] Migrate cli to the latest stable Dart SDK

---

sidekick_core/lib/src/commands/plugins/install_plugin_command.dart

Update error message in `InstallPluginCommand` with update instructions

---

sidekick_core/lib/sidekick_core.dart
sidekick_core/lib/src/version_checker.dart
sidekick_core/test/sidekick_command_runner_test.dart
sk_sidekick/pubspec.lock
sk_sidekick/pubspec.yaml

We discovered, that our update check, which was hidden behind a flag works fine in the wild. Time to enable it for everyone
Land after #180

Enable update check for everyone

---

sk_sidekick/lib/src/commands/release_command.dart
sk_sidekick/pubspec.lock

Tiny improvements, see individual commits :)

Update release script

---

sidekick_core/lib/src/commands/update_command.dart

sidekick update - Ignore `pub get` errors

---

sidekick_vault/pubspec.yaml
sidekick_vault/tool/install.dart

Updated the `sidekick_plugin_installer` dependency in `sidekick_vault`
Switched to `addSelfAsDependency();`
Adressing #191

Update vault installer

---

.github/workflows/integration.yaml

Learning from https://github.com/phntmxyz/sidekick/issues/194

Add integration test for latest `sidekick` version hosted on pub

---

sidekick_vault/pubspec.yaml
sk_sidekick/lib/src/commands/release_command.dart
sk_sidekick/lib/src/sk_project.dart

- `sk release` now asks for the package to be released
- Add some `sleep(1)` to make the whole process easy to follow

Ask for package and make releasing a bit slower and easier to follow

---

sidekick_vault/pubspec.yaml
sidekick_vault/tool/install.dart

promts doesn't fall back to the default value when executed on CI (see https://github.com/phntmxyz/sidekick/actions/runs/3981384358/jobs/6825084494).

Replace promts with dcli

---

sidekick_core/lib/src/update/migration.dart
sidekick_core/lib/src/update/patches/208_remove_cli_name.patch.dart
sidekick_core/lib/src/update/patches/patch_migrations.dart
sidekick_core/test/migration_test.dart
sidekick_core/test/update/patches/208_remove_cli_name.patch_test.dart

Remove name from initializeSidekick() with migration

---

sidekick_vault/example/example.dart
sidekick_vault/lib/src/commands/vault_command.dart
sidekick_vault/pubspec.yaml
sidekick_vault/test/vault_command_test.dart
sidekick_vault/tool/install.dart

Verified install works with
```
./da sidekick plugins install -s git --git-path sidekick_vault --git-ref vault_update_deps https://github.com/phntmxyz/sidekick.git
```

[vault] Update sidekick_core to 1.0.0

---

sidekick/lib/src/commands/init_command.dart
sidekick/pubspec.lock
sidekick/pubspec.yaml
sidekick/test/init_test.dart
sidekick/test/util/cli_runner.dart
sidekick_core/lib/sidekick_core.dart
sidekick_core/lib/src/commands/plugins/create_templates/install_only.dart
sidekick_core/lib/src/commands/plugins/create_templates/shared_code.dart
sidekick_core/lib/src/commands/plugins/create_templates/shared_command.dart
sidekick_core/lib/src/commands/plugins/install_plugin_command.dart

- Update `sidekick_core` in `sidekick`
- Update `sidekick_core` in templates

Fix sidekick tests after core 1.0.0 update

---

sidekick_core/lib/src/update/patches/192_add_format_command.patch.dart
sidekick_core/lib/src/update/patches/patch_migrations.dart
sidekick_core/test/update/patches/192_add_format_command.patch_test.dart

Added the required migration file to install the format command automatically

Adding migration for format command

---

.github/workflows/format.yaml
.github/workflows/integration.yaml
.github/workflows/lint.yaml
.github/workflows/unit_tests.yaml
sidekick/test/init_test.dart
sidekick_core/lib/src/template/sidekick_package.template.dart
sidekick_core/test/deps_command_test.dart
sidekick_core/test/version_checker_test.dart
sidekick_plugin_installer/test/add_dependency_test.dart
sk_sidekick/lib/src/commands/release_command.dart

Cherry-picks from #229, that are unrelated to the update feature

Fix CI on main-1.X

---

sidekick_core/pubspec.yaml

loosen the constraints of `http` package in `sidekick_core`

loose http constraint of sidekick_core

---

sidekick_core/pubspec.yaml

Constrain http to not allow http 2.0.0

constrain http

---

sidekick/test/init_test.dart

Fix the latest failing nightly CI https://github.com/phntmxyz/sidekick/actions/runs/6346779808/job/17240770732

Check for multiple locations of rm

---

sidekick/pubspec.lock

Update CLI dependencies

---

sidekick_core/lib/sidekick_core.dart
sidekick_core/pubspec.yaml

fixes https://github.com/onepub-dev/dcli/issues/242

Hotfix: Constrain dart_console2 dependencies

---

.github/workflows/unit_tests.yaml
sidekick_core/lib/src/update/patches/253_add_lock_file.patch.dart
sidekick_core/lib/src/update/patches/255_dcli_4.patch.dart
sidekick_core/lib/src/update/patches/260_dart_3_5_dcli_7.patch.dart
sidekick_core/test/update_command_test.dart
sidekick_test/lib/src/fake_stdio.dart
sidekick_test/lib/src/local_testing.dart

- Fix `forceAddPubspecLock253` migration (don't crash for missing .gitignore)
- Disable stdin for tests

Fix migrations

---

.github/workflows/unit_tests.yaml
sidekick_core/lib/src/commands/format_command.dart
sidekick_core/lib/src/dart.dart
sidekick_core/test/format_command_test.dart

[Format Dart 3.7] Add support for analysis_options formatter.page_width and remove --fix

---

sidekick_core/analysis_options.yaml
sidekick_core/lib/sidekick_core.dart
sidekick_core/lib/src/file_util.dart
sidekick_core/lib/src/pub/pub.dart
sidekick_core/lib/src/template/sidekick_package.template.dart
sidekick_core/lib/src/update/migration.dart
sidekick_core/lib/src/update/patches/192_add_format_command.patch.dart
sidekick_core/lib/src/update/patches/208_remove_cli_name.patch.dart
sidekick_core/lib/src/update/patches/260_dart_3_5_dcli_7.patch.dart
sidekick_core/test/dart_command_test.dart
sidekick_core/test/init_test.dart
sidekick_core/test/sidekick_package_template_test.dart
sidekick_core/test/version_checker_test.dart
sidekick_test/lib/src/fake_sdk.dart

- Make `makeExecutable` sync
- flush file writes before calling `chmod` (most important!)
- avoid setUp/tearDown

Make CI green

---

.github/workflows/unit_tests.yaml
sidekick_core/lib/src/commands/update_command.dart
sidekick_core/test/update_command_test.dart

- Do not offer older versions then the specific requested one
- Change Test to update to Preview to also test specific updates

Do not offer older versions then the specific requested one also for preview

---

sidekick/test/util/cli_runner.dart
sidekick_core/lib/src/template/download_dart.sh.template.dart
sidekick_core/lib/src/template/entrypoint.template.dart
sidekick_core/lib/src/template/install.sh.template.dart
sidekick_core/lib/src/template/run.sh.template.dart
sidekick_core/lib/src/template/sidekick_config.sh.template.dart

With little effort all bash scripts can become compatible with `/bin/sh`

Convert all bash to sh files for wider compatability
