sidekick/lib/src/init/init_command.dart
sidekick/test/init_test.dart

Before:
User was forced to use `-p` to define a path where sidekick should fulfil its magic
Now:
User can just pass the path into the `init` command without an additional `-p`

Get Path without `-p`

---

.github/workflows/generate.yaml
sidekick/pubspec.lock
sidekick/pubspec.yaml
sidekick/tool/generateTemplate.sh
sidekick/tool/local_mason.dart
sidekick_core/lib/src/file_util.dart
sidekick_core/lib/src/repository.dart

This allows us to use an old mason version that's still compatible with Dart 2.14
Installing the mason CLI on the system doesn't produce a stable output.
- mason has terrible versioning and doesn't follow semver
- pub global activate pulls the latest dependencies. Due to breaking changes inside mason, using the latest dependencies doesn't work (not even compile)
- pinning exact versions in the pubspec.yaml here is the only way to ensure it compiles forever

Pin the mason cli version + dependencies in pubspec

---

sidekick_vault/lib/src/gpg.dart
sidekick_vault/test/vault_command_test.dart

Before, `encrypt` crashed due to 
```
gpg: symmetric encryption of '/Users/pascalwelsch/Downloads/secret.txt' failed: File exists
```

vault encrypt overwrites existing entry

---

README.md

Fixes an analysis error when copying and pasting the example complaining about the missing async.

Fix analysis error in command example in README.md

---

sidekick/lib/src/init/init_command.dart
sidekick/lib/src/init/name_suggester.dart
sidekick/test/init_test.dart

Added validation of CLI name to prevent some errors.
I used the same validation as dart (See https://dart.dev/tools/pub/pubspec#name and https://github.com/dart-lang/sdk/blob/8d262e294400d2f7e41f05579c088a6409a7b2bb/pkg/dartdev/lib/src/utils.dart#L95)
<details>
<summary> `sidekick init` crashes in directory named `_` (which actually is a valid dart package identifier) </summary>
```
❯ dart create _
Creating _ using template console...
...
Created project _ in _! In order to get started, run the following commands:
...
❯ cd _
❯ sidekick init
Welcome to sidekick. You're about to initialize a sidekick project
Please select a name for your sidekick CLI.
We know, selecting a name is hard. Here are some suggestions:
Unhandled exception:
Invalid argument(s): String contained no letters. Cannot …
```

Add CLI name validation

---

sidekick_core/lib/src/dart_package.dart

Our very own sidekick plugin system allows packages without lib folder. While most packages do have a lib folder, it's not a requirement and it's completely fine not to have a lib folder
> At a minimum, a Dart package is a directory containing a [pubspec file](https://dart.dev/tools/pub/pubspec). The pubspec contains some metadata about the package. Additionally, a package can contain dependencies (listed in the pubspec), Dart libraries, apps, resources, tests, images, and examples.
[src](https://dart.dev/guides/packages)

[core] Allow packages without lib folder

---

sidekick_core/lib/sidekick_core.dart
sidekick_core/lib/src/commands/dart_command.dart
sidekick_core/lib/src/commands/flutter_command.dart
sidekick_core/lib/src/dart.dart
sidekick_core/lib/src/flutter.dart
sidekick_core/lib/src/flutterw.dart
sidekick_core/test/dart_command_test.dart
sidekick_core/test/fake_sdk.dart
sidekick_core/test/flutter_command_test.dart
sidekick_core/test/init_test.dart

This change allows pinning the Flutter/Dart SDK using `flutterw`, `fvm` or other mechanisms. 
All that has to change is setting the path in `initializeSidekick()`
```dart
final runner = initializeSidekick(
name: 'dash',
// New
dartSdkPath: 'path/to/dart/sdk',
flutterSdkPath: 'path/to/flutter/sdk',
);
```
Both, `<cli> dart` and `<cli> flutter` now check for those paths and crash otherwise.
API changes:
- Added `dartSdkPath` and `flutterSdkPath` to `initializeSidekick` 
- The `flutterw` is now deprecated in favor of the new `flutter` function
- ~**Breaking:** `flutter()` and `dart()` now don't check for the `flutter_wrapper` `.flutter` dir~
- `flutterw()` and `dart()` now print a warning when using the deprecated `flutter_wrapper` is used implicitly  
- The dart and flutter commands now …

Allow setting flutterSdkPath and dartSdkPath for the flutter and dart commands

---

sidekick/lib/src/init/init_command.dart
sidekick/lib/src/init/name_suggester.dart
sidekick/pubspec.lock
sidekick/pubspec.yaml
sidekick/test/plugins_test.dart
sidekick_core/lib/src/commands/plugins/create_plugin_command.dart
sidekick_core/lib/src/commands/plugins/create_templates/install_only.dart
sidekick_core/lib/src/commands/plugins/create_templates/shared_code.dart
sidekick_core/lib/src/commands/plugins/create_templates/shared_command.dart
sidekick_core/lib/src/commands/plugins/create_templates/template_generator.dart
sidekick_core/pubspec.yaml

Fixes #66, #68, and #69
Plugin templates:
- Generate `analysis_options.yaml` and enable lints
- Generate `.gitignore`
- Generate `README.md`
Also resolves some TODOs after updating to `sidekick_core` v0.8.0

Generate README, .gitignore, and enable lints in plugin templates

---

sidekick_core/lib/src/commands/plugins/create_plugin_command.dart
sidekick_core/lib/src/commands/plugins/create_templates/shared_code.dart
sidekick_core/lib/src/commands/plugins/create_templates/shared_command.dart
sidekick_core/lib/src/commands/plugins/create_templates/template_generator.dart

This creates a typical `package:name/name.dart` import instead of  `package:name/name_command.dart`

Add library to shared-command + shared-code templates

---

sidekick_vault/tool/install.dart

How to test
```bash
<cli> sidekick plugins install -s path ~/github/phntmxyz/sidekick/sidekick_vault  
```
I will publish it now and make it our first plugin :)

Update vault install script to be compatible with latest plugin installer

---

sidekick_core/lib/src/commands/install_global_command.dart

On `sidekick` v0.7.0:
```
❯ ./a sidekick install-global
Unhandled exception:
Unsupported operation: Not supported in zsh
#0      ZshShell.appendToPATH (package:dcli/src/shell/zsh_shell.dart:57)
#1      InstallGlobalCommand._addBinDirToPathOrPrint (package:sidekick_core/src/commands/install_global_command.dart:41)
#2      InstallGlobalCommand.run (package:sidekick_core/src/commands/install_global_command.dart:36)
#3      CommandRunner.runCommand (package:args/command_runner.dart:209)
#4      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:119)
#5      new Future.sync (dart:async/future.dart:302)
#6      CommandRunner.run (package:args/command_runner.dart:119)
#7      SidekickCommandRunner.run (package:sidekick_core/sidekick_core.dart:128)
#8      runA …
```

Fix `install-global` command

---

sidekick/example/README.md
sidekick/lib/sidekick.dart
sidekick_core/example/README.md
sidekick_core/pubspec.yaml
sidekick_plugin_installer/example/README.md
sidekick_vault/example/README.md

1. `sidekick`, `sidekick_core`, and `sidekick_plugin_installer` now have an `example` directory which contains a link to the package's `README.md`: +10 pub points each https://dart.dev/tools/pub/package-layout#examples
2. `sidekick_core` now allows to use the latest `dcli` version (`^1.15.0` instead of `>=1.15.0 <1.31.0`): +10 pub points
<details>
<summary>I tested this with Flutter 2.5.3 and Dart 2.14.4 and it works correctly (the previous version of sidekick_core/pubspec.yaml suggested this wouldn't work because Dart 2.16 would be required with dcli ^1.15.0)</summary>
```
❯ dart --version
Dart SDK version: 2.14.4 (stable) (Wed Oct 13 11:11:32 2021 +0200) on "macos_x64"
❯ flutter --version
Flutter 2.5.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision …
```

Improve pub score by adding `example/README.md` and allowing latest `dcli` version

---

sidekick_core/lib/src/flutter.dart
sidekick_core/test/fake_sdk.dart
sidekick_core/test/flutter_command_test.dart

Currently, when using the [flutterw_sidekick_plugin](https://github.com/passsy/flutterw_sidekick_plugin), there is a problem when running `flutter()` for the first time. Because we only define `flutterSdkPath`, it may happen that the Flutter SDK is not yet downloaded. This leads to an error that can only be resolved by manually calling `./flutterw`.
```
Unhandled exception:
SdkNotFoundException{message: Dart or Flutter SDK set to '/Users/pascalwelsch/Downloads/vgv_start/.flutter', but that directory doesn't exist. Please fix the path in `initializeSidekick` (dartSdkPath/flutterSdkPath). Note that relative sdk paths are resolved relative to the project root, which in this case is '/Users/pascalwelsch/Downloads/vgv_start'.}
#0      _resolveSdkPath …
```

Add addFlutterSdkInitializer

---

sidekick_vault/lib/src/vault.dart
sidekick_vault/test/vault_command_test.dart

Screwing up the file path for `vault encrypt` was showing a wrong error message:
```
Unhandled exception:
random.csv does not exist in vault
#0      SidekickVault.saveFile (package:sidekick_vault/src/vault.dart:63)
#1      _EncryptCommand.run (package:sidekick_vault/src/commands/vault_command.dart:75)
#2      CommandRunner.runCommand (package:args/command_runner.dart:209)
#3      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:119)
#4      new Future.sync (dart:async/future.dart:302)
#5      CommandRunner.run (package:args/command_runner.dart:119)
#6      SidekickCommandRunner.run (package:sidekick_core/sidekick_core.dart:128)
#7      runNoa (package:noa_sidekick/noa_sidekick.dart:65)
#8      main (file:///Users/stevendzionara/noa-frontend/packages/noa_sidekick/bin/ …
```

Improve error message when file doesn't exist

---

.github/workflows/lint.yaml
sidekick_plugin_installer/pubspec.yaml
sidekick_vault/pubspec.yaml

It will be further constrained by `sidekick_core`
This allows us to test for publish warnings

Constrain dcli in every package

---

sidekick/test/plugins_test.dart
sidekick_core/lib/src/template/sidekick_package.template.dart

the sidekick cli package's `build` dir only contains build artifacts and the dart runtime. It may contain dart code, but that should not be analyzed. Therefore ignore it.
Changed the tests to only test for significant parts, so that they don't fail when we change formatting or typos

Ignore the build dir when analyzing

---

sidekick_vault/tool/install.dart

I just discovered that the `README` could not be created because the folder was not yet created. 
Dumb mistake, I did not await the future

Make folder creation sync

---

sidekick/test/recompile_test.dart
sidekick_core/lib/src/commands/plugins/install_plugin_command.dart
sidekick_core/lib/src/template/install.sh.template.dart

Remove stdout from `dart pub get` and `dart compile exe` unless they exit with non-zero exit code.

Minimize stdout when auto compiling the cli

---

sidekick/lib/sidekick.dart
sidekick/test/init_test.dart
sidekick_core/lib/sidekick_core.dart
sidekick_core/test/init_test.dart
sk_sidekick/lib/sk_sidekick.dart
sk_sidekick/lib/src/release/sidekick_bundled_version_bump.dart
sk_sidekick/lib/src/release/sidekick_core_bundled_version_bump.dart

Add `--version` flag to print current sidekick version

---

sidekick_plugin_installer/lib/src/add_dependency.dart
sidekick_plugin_installer/lib/src/plugin_context.dart

Old sidekick clis won't inject it. To be backwards compatible, make it nullable.

Make PluginContext.name nullable

---

sidekick_plugin_installer/lib/src/plugin_context.dart

This allows debugging of plugin installers, by manually executing `install.dart` without calling sidekick install.

Simplify install script path pattern check

---

sidekick/pubspec.lock
sidekick_core/lib/src/template/run.sh.template.dart

Compiling the CLI may write/update the `pubspec.lock` file, causing a different hash. This new has is now saved after compilation

Fix unnecessary recompilation

---

sidekick/lib/src/init/init_command.dart
sidekick_core/lib/src/template/sidekick_package.template.dart
sidekick_core/lib/src/update/migration.dart
sidekick_core/lib/src/update_sidekick_cli.dart
sidekick_core/test/migration_test.dart
sidekick_core/test/update_command_test.dart

To prepare for more migrations (as required by #157) I prepared a tiny migration framework
- Detects which migrations steps to execute
- Allows skipping of failed steps
I converted the current migrations (update tools and update entrypoint) into separate steps which get always executed.
It should now be easy to add new migrations

[Refactor] Use migrations steps for sidekick update

---

sidekick_core/lib/src/template/install.sh.template.dart

When upgrading the dart sdk, or adding new dependencies, the CLI may not be able to compile again. Now, the `install.sh` script runs `pub upgrade` in case of a compilation error and then recompiles.
If the recovery strategy fails, the script restores the previous `pubspec.lock`

Run `pub upgrade` when compilation fails

---

sidekick_core/lib/sidekick_core.dart
sidekick_core/lib/src/cli_util.dart
sidekick_core/lib/src/commands/bash_command.dart
sidekick_core/lib/src/forward_command.dart
sidekick_core/test/bash_command_test.dart

A new command that allows writing a sidekick command as bash script
Usage:
```dart
runner
..addCommand(
BashCommand(
name: 'test-bash-command',
description: 'Prints inputs of a sidekick BashCommand',
workingDirectory: runner.repository.root,
script: () => '''
echo "arguments: \$@"
echo "workingDirectory: \$(pwd)"
${systemFlutterSdkPath()}/bin/flutter --version
''',
),
);
```
Prints
```
❯ sk test-bash-command asdf -s qwer
arguments: asdf -s qwer
working directory: /Users/pascalwelsch/Projects/phntmxyz/sidekick
Flutter 3.3.10 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 135454af32 (3 weeks ago) • 2022-12-15 07:36:55 -0800
Engine • revision 3316dd8728
Tools • Dart 2.18.6 • DevTools 2.15.0
```

Add BashCommand

---

sidekick_core/lib/sidekick_core.dart

This may happen when the dependency is not from pub, but from git or path. Then their version can't be read from pubspec.yaml
Part of #169

Catch _checkCliVersionIntegrity() errors

---

sidekick_core/lib/src/version_checker.dart
sidekick_core/test/version_checker_test.dart

Replaces our existing regex solution with `YamlEditor`. This solves updating a dependency to a pub version that uses a path reference.
```yaml
dependencies:
sidekick_core:
path: ../sidekick_core
```
Now correctly converts to.
```yaml
dependencies:
sidekick_core: ^0.14.0
```
Was converting to this syntax error before:
```yaml
dependencies:
sidekick_core:  ^0.14.0
path: ../sidekick_core
```

Refactor updateVersionConstraint using YamlEditor

---

sidekick_core/lib/src/dart_package.dart
sidekick_core/test/dart_package.dart

dependency `flutter` may not be a `YamlMap`, all we care about is the existence of the dependency

Simplify flutter package detection

---

sidekick_core/lib/src/commands/deps_command.dart
sidekick_core/test/deps_command_test.dart
sidekick_test/lib/src/local_testing.dart

I discovered that the exclusions depended on `cwd`. I fixed the search to repo root

Exclude via glob, starting search at repo root

---

sidekick_core/lib/src/commands/deps_command.dart
sidekick_core/test/deps_command_test.dart
sidekick_test/lib/src/local_testing.dart

Do not load dependencies of the sidekick cli via `deps` because:
- When a user executes the `deps` command, sidekick dependencies are already loaded by the bash scripts
- Sidekick CLIs should only load dependencies using the embedded SDKs
This prevents a constant recompile after each `<cli> deps` because the dependencies change due because the embedded Dart SDK and the `dartSdk` or `flutterSdk` use different dart versions  
Merge after #183

DepsCommand should ignore sidekick cli package

---

sidekick_core/lib/src/template/sidekick_package.template.dart

- fix sidekick_core constraint range
- use dart 2.18.7
- deprecate sidekickCliVersion parameter (it always was the `sidekick_core` version which we can access directly)
Fixes https://github.com/phntmxyz/sidekick/issues/194#issuecomment-1398762605

Default to Dart 2.18.7 with correct sidekick_core version

---

sidekick/.gitignore
sidekick_core/.gitignore
sidekick_plugin_installer/.gitignore
sidekick_vault/.gitignore
sk_sidekick/.gitignore
sk_sidekick/lib/sk_sidekick.dart
sk_sidekick/lib/src/commands/coverage_command.dart

Allows generating code coverage for packages and files
For some reason, I can't get the `run with code coverage` button in IntelliJ working. This allows me to quickly generate coverage without remembering all the commands.

sk coverage

---

sidekick_core/lib/src/commands/plugins/install_plugin_command.dart

I'm currently running into errors during plugin install on ci (https://github.com/phntmxyz/sidekick/actions/runs/3981484188/jobs/6825298249). I have no idea what's wrong, it works well for me locally.
This PR helps further debug plugin installation issues:
- print the exact version of the plugin that was installed
- show pub get errors

Show plugin version during install

---

sidekick_core/lib/src/commands/analyze_command.dart
sidekick_core/lib/src/commands/dart_command.dart
sidekick_core/lib/src/commands/deps_command.dart
sidekick_core/lib/src/commands/flutter_command.dart
sidekick_core/lib/src/commands/update_command.dart
sidekick_core/lib/src/dart.dart
sidekick_core/lib/src/dart_runtime.dart
sidekick_core/lib/src/flutter.dart
sidekick_core/lib/src/flutterw.dart
sidekick_core/test/dart_command_test.dart
sidekick_core/test/dart_test.dart
sidekick_core/test/flutter_command_test.dart
sidekick_core/test/flutter_test.dart
sidekick_core/test/init_test.dart
sidekick_core/test/sidekick_package_template_test.dart
sidekick_test/lib/sidekick_test.dart
sidekick_test/lib/src/delegated_command.dart
sidekick_test/lib/src/fake_sdk.dart
sidekick_test/pubspec.yaml
sk_sidekick/lib/src/commands/lock_dependencies_command.dart
sk_sidekick/lib/src/commands/verify_publish_state_command.dart

Breaking: `flutter` and `dart` throw by default when failing

---

sidekick_core/lib/sidekick_core.dart
sidekick_core/lib/src/version_checker.dart
sidekick_core/test/sidekick_command_runner_test.dart
sidekick_test/lib/src/local_testing.dart

The cli was showing this false positive error message 
```bash
❯ ./da
A sidekick CLI to equip Dart/Flutter projects with custom tasks
Available commands:
analyze    Dart analyzes the whole project
clean      Cleans the project
dart       Calls dart
deps       Gets dependencies for all packages
sidekick   Manages the sidekick CLI
Run "da help <command>" for more information about a command.
Dependency sidekick_core:0.10.0 doesn't match sidekick.cli_version 0.15.1 in your pubspec.yaml.
This is a signal that sidekick_core was updated manually without calling 'sidekick update'. Some features in your CLI might not work as expected.
Please run da sidekick update to execute the missing migrations.
```
It is caused by those `sidekick_core` version definitions:
```yaml
dependencies:
sidekick_core: …
```

Fix misleading update message

---

.github/workflows/lint.yaml
sidekick_core/test/analyzer_command_test.dart
sidekick_core/test/update/patches/208_remove_cli_name.patch_test.dart

Info lints weren't caught by CI. Now they are.
Added tests for proof

Fail for info lints

---

sidekick/pubspec.lock
sidekick/pubspec.yaml
sk_sidekick/lib/src/commands/lock_dependencies_command.dart

I tried to force `sidekick_core: ^1.0.2` but `sk lock-dependencies` always resolved to `sidekick_core: '>=1.0.0 <=1.0.2`. It did not read the constraints from `pubspec.yaml`.
Now it constrains the version correctly.

Lock dependencies should not ignore lower bound constraints

---

sidekick/lib/src/commands/init_command.dart
sidekick/test/init_test.dart

Showing a success message after we successfully run `sidekick init`.
Resolving #36

Show success message after init

---

sidekick_vault/README.md
sidekick_vault/lib/src/commands/vault_command.dart

Updated the vault readme to be up-to date.
- Fixed typo `passpharse` to `passphrase`
- Removed out-dated create vault section
- Add Install section
Addressing Issue #217

Update vault readme

---

sidekick_core/lib/src/template/install.sh.template.dart

Add a third compilation stage that updates major versions. This is especially useful for `0.X` releases.
This should also be backported to `sidekick_core: 0.X`

Allow major versions when upgrading

---

sidekick_core/lib/src/dart_runtime.dart
sidekick_core/lib/src/pub/pub.dart
sidekick_core/lib/src/version_checker.dart
sidekick_core/test/version_checker_test.dart
sidekick_test/lib/src/fake_sdk.dart

In Dart 2.19, the default pub-cache folder changed from `.pub-cache/pub.dartlang.org` to `.pub-cache/pub.dev`. Without this change, InstallPluginCommand would break because we would be looking for the downloaded plugin in the wrong cache folder.

Prepare InstallPluginCommand for use with Dart 2.19 (default pub hosted url changed)

---

sidekick_core/lib/src/commands/format_command.dart
sidekick_core/test/format_command_test.dart

```dart
// ignores *.g.dart and *.freezed.dart files
runner.addCommand(FormatCommand(formatGenerated: false));
```

FormatCommand.formatGenerated allows ignoring generated files (.g.dart)

---

sidekick_core/lib/src/commands/format_command.dart
sidekick_core/test/format_command_test.dart

Fix `FormatCommand` `--verify` exception message, print unformatted files

---

.github/workflows/format.yaml
.github/workflows/integration.yaml
.github/workflows/lint.yaml
.github/workflows/unit_tests.yaml
sidekick/lib/src/commands/init_command.dart
sidekick/pubspec.lock
sidekick/pubspec.yaml
sidekick_core/lib/sidekick_core.dart
sidekick_core/lib/src/dart_package.dart
sidekick_core/lib/src/directory_ext.dart
sidekick_core/lib/src/file_util.dart
sidekick_core/lib/src/sidekick_package.dart
sidekick_core/lib/src/template/sidekick_package.template.dart
sidekick_core/lib/src/update/migration.dart
sidekick_core/pubspec.yaml
sidekick_core/test/deps_command_test.dart
sidekick_core/test/version_checker_test.dart
sidekick_plugin_installer/lib/sidekick_plugin_installer.dart
sidekick_plugin_installer/pubspec.yaml
sidekick_plugin_installer/test/add_dependency_test.dart
sidekick_test/lib/fake_stdio.dart
sidekick_test/lib/src/local_testing.dart
sidekick_test/pubspec.yaml
sidekick_vault/lib/sidekick_vault.dart
sidekick_vault/pubspec.yaml
sidekick_vault/tool/install.dart
sk_sidekick/lib/src/commands/lock_dependencies_command.dart
sk_sidekick/lib/src/commands/release_command.dart
sk_sidekick/pubspec.lock
sk_sidekick/pubspec.yaml

- Become compatible with Dart 3
- Raise min Dart SDK to 2.19
- Update to [dcli:2.2.0](https://pub.dev/packages/dcli/changelog#220), this forces us to upgrade to 2.19. This also causes some breaking changes, hence sidekick_core required a major version bump
- `args` and `path` are now directly exported from `sidekick_core`, where exported from dcli previously
- Become compatible with Dart 3
- Raise min Dart SDK to 2.19
- Use Dart 3 / dcli 2.2.0

[Dart 3] Update sidekick_core & CI

---

sidekick_core/lib/src/template/update_executor.template.dart
sidekick_core/pubspec.yaml
sidekick_core/test/update/update_2_0_0_test.dart

`sidekick_core` transitively depends on `pubspec2` through `dcli`. A new version (`2.5.0`) of `pubspec2` was released today. However, this new version is incompatible with `dcli` `2.2.3` which `sidekick_core` uses. So the transitive dependency has to be constrained to the previously used older version.
https://github.com/onepub-dev/dcli/issues/218
```
../../../.pub-cache/hosted/pub.dev/dcli-2.2.3/lib/src/commands/lock.dart:123:36: Error: Too many positional arguments: 3 allowed, but 4 found.
Try removing the extra positional arguments.
ExternalHostedReference(hosted.package, hosted.url, version, false)
^
../../../.pub-cache/hosted/pub.dev/pubspec2-2.5.0/lib/src/dependency.dart:151:9: Context: Found this candidate, but the arguments don't match.
const ExternalHostedReference(this.name, …
```

Constrain `pubspec2` dependency in `sidekick_core`

---

sidekick/test/plugins_test.dart
sidekick_core/lib/src/commands/plugins/create_templates/install_only.dart
sidekick_core/lib/src/commands/plugins/create_templates/plugin_template_generator.dart
sidekick_core/lib/src/commands/plugins/create_templates/shared_code.dart
sidekick_core/lib/src/commands/plugins/create_templates/shared_command.dart

Fixes #240 
Contains some improvements to other templates as well:
- If plugin name is `foo_sidekick_plugin` (or `sidekick_plugin_foo`), the generated plugin command will be named `foo` now instead of `foo_sidekick_plugin` (or `sidekick_plugin_foo`)
- Generated plugins now have a `topics` field with tags to make finding sidekick plugins easier
- Sample plugin command is now placed in `src/commands`
- When installing `shared-command` plugin now the whole plugin package is imported instead of `src/foo_command.dart`

Fix bug in `shared-command` plugin template when plugin name ends with `_sidekick_plugin`

---

.github/workflows/integration.yaml
sidekick/lib/sidekick.dart
sidekick/lib/src/commands/init_command.dart
sidekick/pubspec.lock
sidekick/pubspec.yaml
sidekick/test/init_test.dart
sidekick/test/tab_completion_test.dart
sidekick/test/test_runner.dart
sidekick/test/util/cli_completion.dart
sidekick/test/util/cli_runner.dart
sidekick_core/lib/sidekick_core.dart
sidekick_core/lib/src/commands/install_global_command.dart
sidekick_core/pubspec.yaml
sidekick_core/test/deps_command_test.dart
sidekick_core/test/format_command_test.dart
sidekick_core/test/sidekick_package_template_test.dart
sidekick_core/test/update/update_2_0_0_test.dart
sidekick_plugin_installer/lib/src/add_dependency.dart
sidekick_test/lib/src/fake_stdio.dart
sidekick_test/lib/src/local_testing.dart
sk_sidekick/pubspec.lock
sk_sidekick/test/sidekick_context_test.dart

- The `sidekick` CLI now has tab completion by default
- Tab completion is enabled in all CLIs using the latest version of `sidekick_core` after running the `sidekick install-global` subcommand. If it isn't enabled yet, prints info about this
The shell completion files are installed after running any command without the need of an additional compilation step 😍 
[cli_completion docs explaining how completion works under the hood](https://github.com/VeryGoodOpenSource/cli_completion/tree/main/doc)

Add tab completion

---

sidekick_core/lib/src/commands/update_command.dart

Don't recommend Dart SDKs where the update would fail.
Waiting for dcli to update to 4.0
or remove dcli from sidekick_core #232

Max Dart SDK 3.2.X

---

sidekick_core/lib/src/commands/format_command.dart
sidekick_core/test/format_command_test.dart

Now includes the package, when explicitly called for a package

Fix SdkInitializerContext.package when calling dart format

---

sidekick_core/pubspec.yaml
sidekick_test/pubspec.yaml

Update to pubspec_manager 1.0.2 to fix an issue with the parsing of a pubspec.yaml with comments.
See: https://github.com/onepub-dev/pubspec_manager/issues/17

Update pubspec_manager to 1.0.2

---

sidekick_core/lib/src/commands/plugins/create_plugin_command.dart
sidekick_core/lib/src/commands/plugins/install_plugin_command.dart
sidekick_core/lib/src/commands/update_command.dart
sidekick_core/lib/src/dart.dart
sidekick_core/lib/src/dart_runtime.dart
sidekick_core/lib/src/update/major_update_dependencies_migration.dart

Since the `dart` function was converted a to a future, The `_dartCommand` was either a future or now future. This lead to the error that the function was sometimes not awaited! 😱
All dart functions are now futures!

[internal] Make all "dart" functions futures

---

.github/workflows/format.yaml
sidekick_core/lib/src/commands/format_command.dart
sidekick_core/test/format_command_test.dart
sk_sidekick/lib/sk_sidekick.dart

Even when entire package where excluded by glob, they where printed to the console
```
Formatting package:package_b
No files to format
Formatting package:package_a
No files to format
Formatting package:minimal
No files to format
Formatting package:minimal_sidekick_plugin
No files to format
Formatting package:minimal
No files to format
Formatting package:root_with_packages
No files to format
Formatting package:sidekick_plugin_installer
Formatted 9 files (0 changed) in 0.20 seconds.
Formatting package:sidekick_vault
Formatted 11 files (0 changed) in 0.25 seconds.
Formatting package:sidekick_test
Formatted 9 files (0 changed) in 0.19 seconds.
Formatting package:sidekick_core
Formatted 77 files (0 changed) in 0.54 seconds.
Formatting package:sk_sidekick
Formatted 13 files (0 changed) in 0.32 …
```

[format] Hide excludeGlob excluded packages entirely from output
